// gravitee-gamma/gravitee-gamma-module-apim/src/main/ui/portal-editor/portal-shell/components/TreeNode.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { useEffect, useState, type CSSProperties } from 'react';

import type { PortalNavigationItem, PortalNavigationItemType, PortalNavigationLink, PortalNavigationPage } from '../../portals/types';
import type { EditorMode } from '../../editor/stores/editor.store';
import { getPageContentTypeLabel, getPageNavIcon, getNavTypeIcon } from '../utils/nav-type-icons';
import { canPublishNavItem, isNavItemPublished, sortNavItemsByOrder } from '../utils/nav-items';
import { isNavContainer } from '../utils/sidebar-context';
import { shouldExpandNode } from '../utils/tree-expand';
import { NavItemContextMenu } from './NavItemContextMenu';
import { EditableLinkNavItem, PreviewLinkNavItem } from './EditableLinkNavItem';
import { NavItemButton } from './NavItemButton';
import navItemStyles from './NavItemButton.module.scss';
import styles from './NavigationTree.module.scss';

interface TreeNodeProps {
    readonly item: PortalNavigationItem;
    readonly allItems: PortalNavigationItem[];
    readonly selectedNavItemId: string | null;
    readonly mode: EditorMode;
    readonly portalId: string;
    readonly portalPages: readonly PortalNavigationPage[];
    readonly depth: number;
    readonly onSelectNavItem: (id: string) => void;
    readonly onAddNavItem: (type: PortalNavigationItemType, parentId: string | null) => void;
    readonly onRequestApi: (parentId: string | null) => void;
    readonly onRequestPage: (parentId: string | null) => void;
    readonly onRequestLink: (parentId: string | null) => void;
    readonly onUpdateNavItem: (id: string, patch: { title?: string; url?: string }) => void;
    readonly onRequestDeleteNavItem: (item: PortalNavigationItem) => void;
    readonly onTogglePublished: (item: PortalNavigationItem) => void;
    readonly instanceOverrides?: Record<string, Record<string, string>>;
    readonly allowedAddTypes?: PortalNavigationItemType[];
    readonly hideStyleActions?: boolean;
}

export function TreeNode({
    item,
    allItems,
    selectedNavItemId,
    mode,
    portalId,
    portalPages,
    depth,
    onSelectNavItem,
    onAddNavItem,
    onRequestApi,
    onRequestPage,
    onRequestLink,
    onUpdateNavItem,
    onRequestDeleteNavItem,
    onTogglePublished,
    instanceOverrides = {},
    allowedAddTypes,
    hideStyleActions = false,
}: TreeNodeProps) {
    const isEditMode = mode === 'edit';
    const isContainer = isNavContainer(item.type);
    const isUnpublished = isEditMode && !isNavItemPublished(item);
    const publishState = canPublishNavItem(item, allItems);
    const children = sortNavItemsByOrder(allItems.filter(navItem => navItem.parentId === item.id));
    const [expanded, setExpanded] = useState(() => shouldExpandNode(allItems, item.id, selectedNavItemId));

    useEffect(() => {
        if (shouldExpandNode(allItems, item.id, selectedNavItemId)) {
            setExpanded(true);
        }
    }, [allItems, item.id, selectedNavItemId]);

    const treeDepthStyle = { '--tree-depth': depth } as CSSProperties;
    const pageIcon =
        item.type === 'PAGE'
            ? getPageNavIcon(item)
            : getNavTypeIcon(item.type);
    const pageTooltip = item.type === 'PAGE' ? getPageContentTypeLabel(item.contentType ?? 'BLOCK') : undefined;

    const nodeButton =
        item.type === 'LINK' && isEditMode ? (
            <EditableLinkNavItem
                item={item as PortalNavigationLink}
                instanceStyle={instanceOverrides[item.id]}
                portalId={portalId}
                portalPages={portalPages}
                selected={selectedNavItemId === item.id}
                showDelete
                variant="sidebar"
                className={navItemStyles.compactLeading}
                icon={pageIcon}
                title={pageTooltip}
                unpublished={isUnpublished}
                onUpdate={patch => onUpdateNavItem(item.id, patch)}
                onDelete={() => onRequestDeleteNavItem(item)}
            />
        ) : item.type === 'LINK' ? (
            <PreviewLinkNavItem
                navItemId={item.id}
                instanceStyle={instanceOverrides[item.id]}
                label={item.title}
                selected={selectedNavItemId === item.id}
                variant="sidebar"
                className={navItemStyles.compactLeading}
                icon={pageIcon}
                onSelect={() => onSelectNavItem(item.id)}
            />
        ) : (
            <NavItemButton
                navItemId={item.id}
                instanceStyle={instanceOverrides[item.id]}
                label={item.title}
                selected={selectedNavItemId === item.id}
                showDelete={isEditMode}
                variant="sidebar"
                className={navItemStyles.compactLeading}
                icon={pageIcon}
                title={pageTooltip}
                unpublished={isUnpublished}
                onSelect={() => onSelectNavItem(item.id)}
                onDelete={() => onRequestDeleteNavItem(item)}
                onLabelChange={isEditMode ? title => onUpdateNavItem(item.id, { title }) : undefined}
            />
        );

    const row = (
        <div className={styles.row}>
            {isContainer ? (
                <button
                    type="button"
                    className={`${styles.chevron} ${expanded ? styles.chevronExpanded : ''}`}
                    aria-label={expanded ? `Collapse ${item.title}` : `Expand ${item.title}`}
                    aria-expanded={expanded}
                    onClick={event => {
                        event.stopPropagation();
                        setExpanded(current => !current);
                    }}
                >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <polyline points="9 18 15 12 9 6" />
                    </svg>
                </button>
            ) : (
                <span className={styles.chevronSpacer} aria-hidden="true" />
            )}
            <div className={styles.nodeButton}>{nodeButton}</div>
        </div>
    );

    return (
        <div className={styles.treeNode} style={treeDepthStyle}>
            <NavItemContextMenu
                item={item}
                allItems={allItems}
                enabled={isEditMode}
                isContainer={isContainer}
                onAdd={onAddNavItem}
                onRequestApi={onRequestApi}
                onRequestPage={onRequestPage}
                onRequestLink={onRequestLink}
                onTogglePublished={onTogglePublished}
                publishDisabled={!publishState.allowed}
                publishDisabledReason={publishState.reason}
                allowedAddTypes={allowedAddTypes}
                hideStyleActions={hideStyleActions}
            >
                {row}
            </NavItemContextMenu>
            {isContainer && expanded && (
                <div className={styles.children}>
                    {children.map(child => (
                        <TreeNode
                            key={child.id}
                            item={child}
                            allItems={allItems}
                            selectedNavItemId={selectedNavItemId}
                            mode={mode}
                            portalId={portalId}
                            portalPages={portalPages}
                            depth={depth + 1}
                            onSelectNavItem={onSelectNavItem}
                            onAddNavItem={onAddNavItem}
                            onRequestApi={onRequestApi}
                            onRequestPage={onRequestPage}
                            onRequestLink={onRequestLink}
                            onUpdateNavItem={onUpdateNavItem}
                            onRequestDeleteNavItem={onRequestDeleteNavItem}
                            onTogglePublished={onTogglePublished}
                            instanceOverrides={instanceOverrides}
                            allowedAddTypes={allowedAddTypes}
                            hideStyleActions={hideStyleActions}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}

// gravitee-apim-portal-webui-next/src/app/documentation/components/documentation-folder/tree-component/tree-node.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';

import { SectionNode } from './tree.component';
import { PortalNavigationLink } from '../../../../../entities/portal-navigation/portal-navigation-item';

@Component({
  selector: 'app-tree-node',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatButtonModule],
  templateUrl: './tree-node.component.html',
  styleUrls: ['./tree-node.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeNodeComponent {
  node = input.required<SectionNode>();
  level = input(0);
  selectedId = input<string | null>(null);

  nodeSelected = output<string>();

  isSelected = computed(() => this.selectedId() === this.node().id);
  isExpanded = signal<boolean>(true);

  selectNode(): void {
    this.nodeSelected.emit(this.node().id);
  }

  toggleNode(): void {
    this.isExpanded.update(v => !v);
  }

  onClick() {
    switch (this.node().type) {
      case 'FOLDER':
        this.toggleNode();
        break;
      case 'PAGE':
        this.selectNode();
        break;
      case 'LINK': {
        const link = this.node().data as PortalNavigationLink;
        window.open(link.url, '_blank');
        break;
      }
    }
  }
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<div
  class="tree__row"
  role="treeitem"
  tabindex="0"
  [class.selected]="isSelected()"
  [class.folder]="node().type === 'FOLDER'"
  [class.child]="level() > 0"
  [style.--level]="level()"
  [attr.aria-level]="level() + 1"
  [attr.aria-selected]="isSelected()"
  [attr.aria-expanded]="node().type === 'FOLDER' ? isExpanded() : null"
  (click)="onClick()"
  (keydown.enter)="onClick()"
  (keydown.arrowright)="node().type === 'FOLDER' && isExpanded.set(true)"
  (keydown.arrowleft)="node().type === 'FOLDER' && isExpanded.set(false)">
  @if (node().type === 'FOLDER') {
    <mat-icon
      class="tree__icon"
      [attr.data-test-icon]="'toggle'"
      [fontIcon]="isExpanded() ? 'keyboard_arrow_down' : 'keyboard_arrow_right'"
      aria-hidden="true"
      (click)="toggleNode(); $event.stopPropagation()" />
  }
  <span class="tree__label">{{ node().label }}</span>
</div>

@if (node().children?.length && isExpanded()) {
  <div class="tree__children">
    @for (child of node().children; track child) {
      <app-tree-node
        [attr.id]="'node-' + child.id"
        [node]="child"
        [level]="level() + 1"
        [selectedId]="selectedId()"
        (nodeSelected)="nodeSelected.emit($event)" />
    }
  </div>
}
