// gravitee-apim-portal-gamma/src/shared/components/ConfirmDialog.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {
    Button,
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    Input,
    Label,
} from '@gravitee/graphene-core';
import { useEffect, useId, useState, type ReactNode } from 'react';

export interface ConfirmDialogProps {
    readonly open: boolean;
    readonly onOpenChange: (open: boolean) => void;
    readonly title: ReactNode;
    readonly description?: ReactNode;
    readonly confirmLabel: string;
    readonly pendingLabel?: string;
    readonly cancelLabel?: string;
    readonly destructive?: boolean;
    readonly isPending?: boolean;
    readonly confirmKeyword?: string;
    readonly icon?: ReactNode;
    readonly onConfirm: () => void;
}

export function ConfirmDialog({
    open,
    onOpenChange,
    title,
    description,
    confirmLabel,
    pendingLabel,
    cancelLabel = 'Cancel',
    destructive = false,
    isPending = false,
    confirmKeyword,
    icon,
    onConfirm,
}: ConfirmDialogProps) {
    const inputId = useId();
    const [typed, setTyped] = useState('');

    useEffect(() => {
        if (!open) {
            setTyped('');
        }
    }, [open]);

    const keywordSatisfied = !confirmKeyword || typed === confirmKeyword;
    const disabled = isPending || !keywordSatisfied;

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="w-full max-w-md sm:max-w-md" showCloseButton={false}>
                <DialogHeader>
                    <DialogTitle>{title}</DialogTitle>
                    {description ? <DialogDescription>{description}</DialogDescription> : null}
                </DialogHeader>
                {confirmKeyword ? (
                    <div className="space-y-2 py-2">
                        <Label htmlFor={inputId} className="text-sm">
                            Type <span className="font-mono font-semibold">{confirmKeyword}</span> to confirm
                        </Label>
                        <Input
                            id={inputId}
                            value={typed}
                            onChange={e => setTyped(e.target.value)}
                            placeholder={confirmKeyword}
                            autoComplete="off"
                        />
                    </div>
                ) : null}
                <DialogFooter className="sm:justify-end">
                    <DialogClose asChild>
                        <Button type="button" variant="outline" disabled={isPending}>
                            {cancelLabel}
                        </Button>
                    </DialogClose>
                    <Button
                        type="button"
                        variant={destructive ? 'destructive' : 'default'}
                        disabled={disabled}
                        onClick={onConfirm}
                    >
                        {icon}
                        {isPending ? (pendingLabel ?? `${confirmLabel}…`) : confirmLabel}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}

// src/shared/components/confirm-dialog/confirm-dialog.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';

export type GioConfirmDialogData = {
  title?: string;
  content?: string;
  confirmButton?: string;
  cancelButton?: string;
};

@Component({
  selector: 'gio-confirm-dialog',
  template: require('./confirm-dialog.component.html'),
})
export class GioConfirmDialogComponent {
  title: string;
  content?: string;
  confirmButton: string;
  cancelButton: string;

  constructor(public dialogRef: MatDialogRef<GioConfirmDialogComponent>, @Inject(MAT_DIALOG_DATA) confirmDialogData: GioConfirmDialogData) {
    this.title = confirmDialogData?.title ?? 'Are you sure ?';
    this.content = confirmDialogData?.content;
    this.confirmButton = confirmDialogData?.confirmButton ?? 'Yes';
    this.cancelButton = confirmDialogData?.cancelButton ?? 'Cancel';
  }
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<h2 mat-dialog-title class="confirm-dialog__title">{{ title }}</h2>

<mat-dialog-content *ngIf="content" class="confirm-dialog__content">
  <p>{{ content }}</p>
</mat-dialog-content>

<mat-dialog-actions align="end" class="confirm-dialog__actions">
  <button class="confirm-dialog__cancel-button" mat-button color="accent" [mat-dialog-close]="false">
    {{ cancelButton }}
  </button>
  <button class="confirm-dialog__confirm-button" color="warn" mat-button mat-raised-button [mat-dialog-close]="true" cdkFocusInitial>
    {{ confirmButton }}
  </button>
</mat-dialog-actions>
