// gravitee-apim-portal-gamma/src/features/portal-shell/components/TreeNode.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { useEffect, useState, type CSSProperties } from 'react';

import type { PortalNavigationItem, PortalNavigationItemType } from '../../portals/types';
import type { EditorMode } from '../../editor/stores/editor.store';
import { getNavTypeIcon } from '../utils/nav-type-icons';
import { isNavContainer } from '../utils/sidebar-context';
import { shouldExpandNode } from '../utils/tree-expand';
import { NavItemButton } from './NavItemButton';
import navItemStyles from './NavItemButton.module.scss';
import { TreeAddButton } from './TreeAddButton';
import styles from './NavigationTree.module.scss';

interface TreeNodeProps {
    readonly item: PortalNavigationItem;
    readonly allItems: PortalNavigationItem[];
    readonly selectedNavItemId: string | null;
    readonly mode: EditorMode;
    readonly depth: number;
    readonly onSelectNavItem: (id: string) => void;
    readonly onAddNavItem: (type: PortalNavigationItemType, parentId: string | null) => void;
    readonly onRequestApi: (parentId: string | null) => void;
    readonly onUpdateNavItem: (id: string, patch: { title?: string }) => void;
    readonly onRequestDeleteNavItem: (item: PortalNavigationItem) => void;
}

export function TreeNode({
    item,
    allItems,
    selectedNavItemId,
    mode,
    depth,
    onSelectNavItem,
    onAddNavItem,
    onRequestApi,
    onUpdateNavItem,
    onRequestDeleteNavItem,
}: TreeNodeProps) {
    const isEditMode = mode === 'edit';
    const isContainer = isNavContainer(item.type);
    const children = allItems
        .filter(navItem => navItem.parentId === item.id)
        .sort((left, right) => left.order - right.order);
    const [expanded, setExpanded] = useState(() => shouldExpandNode(allItems, item.id, selectedNavItemId));

    useEffect(() => {
        if (shouldExpandNode(allItems, item.id, selectedNavItemId)) {
            setExpanded(true);
        }
    }, [allItems, item.id, selectedNavItemId]);

    const treeDepthStyle = { '--tree-depth': depth } as CSSProperties;

    return (
        <div className={styles.treeNode} style={treeDepthStyle}>
            <div className={styles.row}>
                {isContainer ? (
                    <button
                        type="button"
                        className={`${styles.chevron} ${expanded ? styles.chevronExpanded : ''}`}
                        aria-label={expanded ? `Collapse ${item.title}` : `Expand ${item.title}`}
                        aria-expanded={expanded}
                        onClick={event => {
                            event.stopPropagation();
                            setExpanded(current => !current);
                        }}
                    >
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                            <polyline points="9 18 15 12 9 6" />
                        </svg>
                    </button>
                ) : (
                    <span className={styles.chevronSpacer} aria-hidden="true" />
                )}
                <div className={styles.nodeButton}>
                    <NavItemButton
                        label={item.title}
                        selected={selectedNavItemId === item.id}
                        showDelete={isEditMode}
                        variant="sidebar"
                        className={navItemStyles.compactLeading}
                        icon={getNavTypeIcon(item.type)}
                        onSelect={() => onSelectNavItem(item.id)}
                        onDelete={() => onRequestDeleteNavItem(item)}
                        onLabelChange={isEditMode ? title => onUpdateNavItem(item.id, { title }) : undefined}
                    />
                </div>
            </div>
            {isContainer && expanded && (
                <>
                    <div className={styles.children}>
                        {children.map(child => (
                            <TreeNode
                                key={child.id}
                                item={child}
                                allItems={allItems}
                                selectedNavItemId={selectedNavItemId}
                                mode={mode}
                                depth={depth + 1}
                                onSelectNavItem={onSelectNavItem}
                                onAddNavItem={onAddNavItem}
                                onRequestApi={onRequestApi}
                                onUpdateNavItem={onUpdateNavItem}
                                onRequestDeleteNavItem={onRequestDeleteNavItem}
                            />
                        ))}
                    </div>
                    {isEditMode && (
                        <TreeAddButton
                            parentId={item.id}
                            depth={depth + 1}
                            onAdd={onAddNavItem}
                            onRequestApi={onRequestApi}
                        />
                    )}
                </>
            )}
        </div>
    );
}

// gravitee-apim-console-webui/src/portal/components/tree-component/tree-node.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

import { SectionNode } from './tree.component';

@Component({
  selector: 'app-tree-node',
  standalone: true,
  imports: [CommonModule, MatIconModule, TreeNodeComponent],
  templateUrl: './tree-node.component.html',
  styleUrls: ['./tree-node.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeNodeComponent {
  node = input.required<SectionNode>();
  level = input(0);
  selectedId = input<string | null>(null);

  nodeSelected = output<SectionNode>();

  isSelected = computed(() => this.selectedId() === this.node().id);
  isExpanded = signal<boolean>(true);

  selectNode(): void {
    this.nodeSelected.emit(this.node());
  }

  toggleNode(): void {
    this.isExpanded.update((v) => !v);
  }
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<div
  class="tree__row"
  [class.unpublished]="node().data?.published === false"
  role="treeitem"
  tabindex="0"
  [class.selected]="isSelected()"
  [class.folder]="node().type === 'FOLDER'"
  [class.child]="level() > 0"
  [style.--level]="level()"
  [attr.aria-level]="level() + 1"
  [attr.aria-selected]="isSelected()"
  [attr.aria-expanded]="node().type === 'FOLDER' ? isExpanded() : null"
  (click)="selectNode()"
  (keydown.enter)="selectNode()"
  (keydown.arrowright)="node().type === 'FOLDER' && isExpanded.set(true)"
  (keydown.arrowleft)="node().type === 'FOLDER' && isExpanded.set(false)"
>
  @if (node().type === 'FOLDER') {
    <mat-icon
      class="tree__icon"
      [attr.data-test-icon]="'toggle'"
      [svgIcon]="isExpanded() ? 'gio:nav-arrow-down' : 'gio:nav-arrow-right'"
      aria-hidden="true"
      (click)="toggleNode(); $event.stopPropagation()"
    />
  }

  <mat-icon
    class="tree__icon tree__icon__type"
    [attr.data-test-type]="node().type"
    svgIcon="gio:{{ node().type | lowercase }}"
    aria-hidden="true"
  />

  <span class="tree__label">{{ node().label }}</span>

  @if (node().data?.published === false) {
    <mat-icon class="tree__icon tree__icon__status" svgIcon="gio:eye-off" aria-hidden="true" [attr.data-test-icon]="'eye-off'" />
  }

  <button
    type="button"
    mat-icon-button
    class="tree__button more-actions"
    aria-label="More actions"
    [matMenuTriggerFor]="moreMenu"
    (click)="$event.stopPropagation()"
    *gioPermission="{ anyOf: ['environment-documentation-u', 'environment-documentation-d'] }"
  >
    <mat-icon svgIcon="gio:more-vertical" />
  </button>
  <mat-menu #moreMenu="matMenu">
    @if (node()?.type === 'FOLDER') {
      <button mat-menu-item (click)="triggerCreate('PAGE')">
        <mat-icon svgIcon="gio:page"></mat-icon>
        Add Page
      </button>
      <button mat-menu-item (click)="triggerCreate('FOLDER')">
        <mat-icon svgIcon="gio:folder"></mat-icon>
        Add Folder
      </button>
      <button mat-menu-item (click)="triggerCreate('LINK')">
        <mat-icon svgIcon="gio:link"></mat-icon>
        Add Link
      </button>
    }
    <mat-divider></mat-divider>
    <button mat-menu-item (click)="triggerEdit()">
      <mat-icon svgIcon="gio:edit-pencil"></mat-icon>
      Edit
    </button>
  </mat-menu>
</div>

@if (node().children?.length && isExpanded()) {
  <div class="tree__children">
    @for (child of node().children; track child) {
      <app-tree-node
        [node]="child"
        [level]="level() + 1"
        [selectedId]="selectedId()"
        (nodeSelected)="nodeSelected.emit($event)"
        (nodeMenuAction)="nodeMenuAction.emit($event)"
      />
    }
  </div>
}
