// gravitee-gamma/gravitee-gamma-module-platform/src/main/ui/features/users/components/UserAvatar.tsx
/*
 * Copyright © 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Avatar, AvatarFallback } from '@gravitee/graphene-core';

export function UserAvatar({ name }: Readonly<{ name: string }>) {
    const initials = name
        .split(' ')
        .map(part => part[0] ?? '')
        .join('')
        .toUpperCase()
        .slice(0, 2);

    return (
        <Avatar size="sm" className="shrink-0">
            <AvatarFallback className="bg-primary/10 text-primary text-xs font-semibold">{initials || '?'}</AvatarFallback>
        </Avatar>
    );
}

// src/app/components/user-avatar/user-avatar.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {Component, Input, OnInit} from '@angular/core';
import {User} from '@gravitee/ng-portal-webclient';
import jdenticon from 'jdenticon';

@Component({
  selector: 'app-user-avatar',
  templateUrl: './user-avatar.component.html'
})
export class UserAvatarComponent implements OnInit {

  public hasError: boolean;
  @Input() user: User;
  @Input() size: number = Number(40);

  constructor() {
    this.hasError = false;
  }

  ngOnInit() {
  }

  getDefaultAvatar() {
    return jdenticon.toSvg(this.user.display_name, this.size);
  }

}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<gv-image *ngIf="!hasError" src="{{user._links.avatar}}" alt="{{user.display_name}}"
          [style]="getRoundedStyle() | safe: 'style'" (error)="hasError=true"></gv-image>
<span *ngIf="hasError" [innerHTML]="getDefaultAvatar() | safe: 'html'" title="{{ user.display_name }}">
