// gravitee-apim-portal-webui-next/src/app/documentation/components/documentation-folder/tree-component/tree-node.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

import { SectionNode } from './tree.component';

@Component({
  selector: 'app-tree-node',
  standalone: true,
  imports: [CommonModule, MatIconModule, MatButtonModule],
  templateUrl: './tree-node.component.html',
  styleUrls: ['./tree-node.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TreeNodeComponent {
  node = input.required<SectionNode>();
  level = input(0);
  selectedId = input<string | null>(null);

  nodeSelected = output<string>();

  isSelected = computed(() => this.selectedId() === this.node().id);
  isExpanded = signal<boolean>(true);

  selectNode(): void {
    this.nodeSelected.emit(this.node().id);
  }

  toggleNode(): void {
    this.isExpanded.update((v) => !v);
  }
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<div
  class="tree__row"
  role="treeitem"
  tabindex="0"
  [class.selected]="isSelected()"
  [class.folder]="node().type === 'FOLDER'"
  [class.child]="level() > 0"
  [style.--level]="level()"
  [attr.aria-level]="level() + 1"
  [attr.aria-selected]="isSelected()"
  [attr.aria-expanded]="node().type === 'FOLDER' ? isExpanded() : null"
  (click)="node().type === 'FOLDER' ? toggleNode() : selectNode()"
  (keydown.enter)="selectNode()"
  (keydown.arrowright)="node().type === 'FOLDER' && isExpanded.set(true)"
  (keydown.arrowleft)="node().type === 'FOLDER' && isExpanded.set(false)"
>
  @if (node().type === 'FOLDER') {
    <mat-icon
      class="tree__icon"
      [attr.data-test-icon]="'toggle'"
      [fontIcon]="isExpanded() ? 'keyboard_arrow_down' : 'keyboard_arrow_right'"
      aria-hidden="true"
      (click)="toggleNode(); $event.stopPropagation()"
    />
  }

<!--    svgIcon="gio:{{ node().type | lowercase }}"-->
  <mat-icon
    class="tree__icon tree__icon__type"
    [attr.data-test-type]="node().type"
    aria-hidden="true"
  />

  <span class="tree__label">{{ node().label }}</span>

  <button type="button" mat-icon-button class="tree__button more-actions" aria-label="More actions" (click)="$event.stopPropagation()">
<!--    <mat-icon svgIcon="gio:more-vertical" />-->
  </button>
</div>

@if (node().children?.length && isExpanded()) {
  <div class="tree__children">
    @for (child of node().children; track child) {
      <app-tree-node [node]="child" [level]="level() + 1" [selectedId]="selectedId()" (nodeSelected)="nodeSelected.emit($event)" />
    }
  </div>
}

// gravitee-apim-portal-gamma/src/features/portal-shell/components/TreeNode.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { useEffect, useState, type CSSProperties } from 'react';

import type { PortalNavigationItem, PortalNavigationItemType } from '../../portals/types';
import type { EditorMode } from '../../editor/stores/editor.store';
import { getNavTypeIcon } from '../utils/nav-type-icons';
import { sortNavItemsByOrder } from '../utils/nav-items';
import { isNavContainer } from '../utils/sidebar-context';
import { shouldExpandNode } from '../utils/tree-expand';
import { AddNavItemContextMenu } from './AddNavItemContextMenu';
import { NavItemButton } from './NavItemButton';
import navItemStyles from './NavItemButton.module.scss';
import styles from './NavigationTree.module.scss';

interface TreeNodeProps {
    readonly item: PortalNavigationItem;
    readonly allItems: PortalNavigationItem[];
    readonly selectedNavItemId: string | null;
    readonly mode: EditorMode;
    readonly depth: number;
    readonly onSelectNavItem: (id: string) => void;
    readonly onAddNavItem: (type: PortalNavigationItemType, parentId: string | null) => void;
    readonly onRequestApi: (parentId: string | null) => void;
    readonly onUpdateNavItem: (id: string, patch: { title?: string }) => void;
    readonly onRequestDeleteNavItem: (item: PortalNavigationItem) => void;
}

export function TreeNode({
    item,
    allItems,
    selectedNavItemId,
    mode,
    depth,
    onSelectNavItem,
    onAddNavItem,
    onRequestApi,
    onUpdateNavItem,
    onRequestDeleteNavItem,
}: TreeNodeProps) {
    const isEditMode = mode === 'edit';
    const isContainer = isNavContainer(item.type);
    const children = sortNavItemsByOrder(allItems.filter(navItem => navItem.parentId === item.id));
    const [expanded, setExpanded] = useState(() => shouldExpandNode(allItems, item.id, selectedNavItemId));

    useEffect(() => {
        if (shouldExpandNode(allItems, item.id, selectedNavItemId)) {
            setExpanded(true);
        }
    }, [allItems, item.id, selectedNavItemId]);

    const treeDepthStyle = { '--tree-depth': depth } as CSSProperties;

    const row = (
        <div className={styles.row}>
            {isContainer ? (
                <button
                    type="button"
                    className={`${styles.chevron} ${expanded ? styles.chevronExpanded : ''}`}
                    aria-label={expanded ? `Collapse ${item.title}` : `Expand ${item.title}`}
                    aria-expanded={expanded}
                    onClick={event => {
                        event.stopPropagation();
                        setExpanded(current => !current);
                    }}
                >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <polyline points="9 18 15 12 9 6" />
                    </svg>
                </button>
            ) : (
                <span className={styles.chevronSpacer} aria-hidden="true" />
            )}
            <div className={styles.nodeButton}>
                <NavItemButton
                    label={item.title}
                    selected={selectedNavItemId === item.id}
                    showDelete={isEditMode}
                    variant="sidebar"
                    className={navItemStyles.compactLeading}
                    icon={getNavTypeIcon(item.type)}
                    onSelect={() => onSelectNavItem(item.id)}
                    onDelete={() => onRequestDeleteNavItem(item)}
                    onLabelChange={isEditMode ? title => onUpdateNavItem(item.id, { title }) : undefined}
                />
            </div>
        </div>
    );

    return (
        <div className={styles.treeNode} style={treeDepthStyle}>
            <AddNavItemContextMenu
                parentId={item.id}
                allItems={allItems}
                enabled={isEditMode && isContainer}
                onAdd={onAddNavItem}
                onRequestApi={onRequestApi}
            >
                {row}
            </AddNavItemContextMenu>
            {isContainer && expanded && (
                <div className={styles.children}>
                    {children.map(child => (
                        <TreeNode
                            key={child.id}
                            item={child}
                            allItems={allItems}
                            selectedNavItemId={selectedNavItemId}
                            mode={mode}
                            depth={depth + 1}
                            onSelectNavItem={onSelectNavItem}
                            onAddNavItem={onAddNavItem}
                            onRequestApi={onRequestApi}
                            onUpdateNavItem={onUpdateNavItem}
                            onRequestDeleteNavItem={onRequestDeleteNavItem}
                        />
                    ))}
                </div>
            )}
        </div>
    );
}
