// gravitee-apim-portal-gamma/src/features/portal-shell/components/PortalHeader.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import type { PortalNavigationItem, PortalNavigationItemType, PortalNavigationPage } from '../../portals/types';
import type { EditorMode } from '../../editor/stores/editor.store';
import { AddNavItemDropdown } from './AddNavItemDropdown';
import { NavItemButton } from './NavItemButton';
import { PortalIconEditor } from './PortalIconEditor';
import { UserMenu, type UserMenuShellProps } from './UserMenu';
import styles from './PortalHeader.module.scss';

interface PortalHeaderProps {
    readonly portalId: string;
    readonly portalIconUrl: string;
    readonly rootItems: PortalNavigationItem[];
    readonly selectedNavItemId: string | null;
    readonly mode: EditorMode;
    readonly onSelectNavItem: (id: string) => void;
    readonly onAddNavItem: (type: PortalNavigationItemType, parentId: string | null) => void;
    readonly onUpdateNavItem: (id: string, patch: { title?: string }) => void;
    readonly onPortalIconChange: (portalIconUrl: string) => void;
    readonly onRequestDeleteNavItem: (item: PortalNavigationItem) => void;
    readonly userMenuProps: UserMenuShellProps;
    readonly portalPages: readonly PortalNavigationPage[];
    readonly getPagePath: (slug: string) => string;
    readonly onNavigate?: (path: string, options?: { replace?: boolean }) => void;
}

export function PortalHeader({
    portalId,
    portalIconUrl,
    rootItems,
    selectedNavItemId,
    mode,
    onSelectNavItem,
    onAddNavItem,
    onUpdateNavItem,
    onPortalIconChange,
    onRequestDeleteNavItem,
    userMenuProps,
    portalPages,
    getPagePath,
    onNavigate,
}: PortalHeaderProps) {
    const isEditMode = mode === 'edit';

    return (
        <header className={`${styles.header} portal-editable-region`}>
            <div className={styles.left}>
                <PortalIconEditor
                    portalIconUrl={portalIconUrl}
                    editable={isEditMode}
                    onChange={onPortalIconChange}
                />
            </div>

            <nav className={styles.nav}>
                {rootItems.map(item => (
                    <NavItemButton
                        key={item.id}
                        label={item.title}
                        selected={selectedNavItemId === item.id}
                        showDelete={isEditMode}
                        variant="header"
                        className={styles.navButton}
                        onSelect={() => onSelectNavItem(item.id)}
                        onDelete={() => onRequestDeleteNavItem(item)}
                        onLabelChange={isEditMode ? title => onUpdateNavItem(item.id, { title }) : undefined}
                    />
                ))}
                {isEditMode && (
                    <AddNavItemDropdown
                        allowedTypes={['FOLDER', 'PAGE', 'LINK']}
                        parentId={null}
                        onAdd={onAddNavItem}
                    />
                )}
            </nav>

            <div className={styles.right}>
                <UserMenu
                    {...userMenuProps}
                    mode={mode}
                    portalId={portalId}
                    portalPages={portalPages}
                    getPagePath={getPagePath}
                    onNavigate={onNavigate}
                    className={styles.userIcon}
                />
            </div>
        </header>
    );
}

// gravitee-apim-console-webui/src/portal/components/header/portal-header.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Component, InputSignal, input } from '@angular/core';

@Component({
  selector: 'portal-header',
  templateUrl: './portal-header.component.html',
  styleUrl: './portal-header.component.scss',
})
export class PortalHeaderComponent {
  title: InputSignal<string> = input.required();
  subtitle: InputSignal<string> = input();
  showActions: InputSignal<boolean> = input(false);
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<div class="portal-header">
  <div class="portal-header__content">
    <div>
      <div class="portal-header__title-row">
        <div class="mat-h2">
          {{ title() }}
          <ng-content select="[badge]" />
        </div>
      </div>
      @if (subtitle()) {
        <div class="portal-header__subtitle mat-body-2">{{ subtitle() }}</div>
      }
    </div>
    @if (showActions()) {
      <ng-content select="[additionalActions]" />
    }
  </div>

  @if (showTechPreviewMessage()) {
    <gio-banner-info>
      {{ techPreviewMessage }}
    </gio-banner-info>
  }
</div>
