// gravitee-apim-portal-gamma/src/pages/HomePage.tsx
/*
 * Copyright (C) 2026 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export function HomePage() {
    return (
        <div>
            <h1>Gravitee Portal</h1>
            <p>Portal Gamma shell — ready for development.</p>
        </div>
    );
}

// gravitee-apim-portal-webui-next/src/app/homepage/homepage.component.ts
/*
 * Copyright (C) 2025 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Copyright (C) 2025 The Gravitee team
 */
import { Component, input } from '@angular/core';

import { NavigationItemContentViewerComponent } from '../../components/navigation-item-content-viewer/navigation-item-content-viewer.component';
import { PortalPageContent } from '../../entities/portal-navigation/portal-page-content';

@Component({
  selector: 'app-homepage',
  imports: [NavigationItemContentViewerComponent],
  template: `<div class="content"><app-navigation-item-content-viewer [pageContent]="pageContent()" /></div>`,
  styleUrls: ['./homepage.component.scss'],
})
export class HomepageComponent {
  pageContent = input.required<PortalPageContent>();
}

<gravitee-markdown-viewer [content]="content" appInnerLink></gravitee-markdown-viewer>
